// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: proto/entityTypeDefine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_EntityTypeAll EntityType = 0
	// 玩家
	EntityType_EntityTypePlayer EntityType = 1
	// 怪物
	EntityType_EntityTypeMonster EntityType = 2
	// 掉落物
	EntityType_EntityTypeFallingObject EntityType = 3
	// 客户端专用，主角
	EntityType_MainPlayer EntityType = 4
	// 最大值
	EntityType_EntityTypeMax EntityType = 5
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "EntityTypeAll",
		1: "EntityTypePlayer",
		2: "EntityTypeMonster",
		3: "EntityTypeFallingObject",
		4: "MainPlayer",
		5: "EntityTypeMax",
	}
	EntityType_value = map[string]int32{
		"EntityTypeAll":           0,
		"EntityTypePlayer":        1,
		"EntityTypeMonster":       2,
		"EntityTypeFallingObject": 3,
		"MainPlayer":              4,
		"EntityTypeMax":           5,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_entityTypeDefine_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_proto_entityTypeDefine_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_proto_entityTypeDefine_proto_rawDescGZIP(), []int{0}
}

var File_proto_entityTypeDefine_proto protoreflect.FileDescriptor

var file_proto_entityTypeDefine_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2a,
	0x8c, 0x01, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11,
	0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x41, 0x6c, 0x6c, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x10, 0x02, 0x12, 0x1b,
	0x0a, 0x17, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x46, 0x61, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4d,
	0x61, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x61, 0x78, 0x10, 0x05, 0x42, 0x13,
	0x5a, 0x11, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_entityTypeDefine_proto_rawDescOnce sync.Once
	file_proto_entityTypeDefine_proto_rawDescData = file_proto_entityTypeDefine_proto_rawDesc
)

func file_proto_entityTypeDefine_proto_rawDescGZIP() []byte {
	file_proto_entityTypeDefine_proto_rawDescOnce.Do(func() {
		file_proto_entityTypeDefine_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_entityTypeDefine_proto_rawDescData)
	})
	return file_proto_entityTypeDefine_proto_rawDescData
}

var file_proto_entityTypeDefine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_entityTypeDefine_proto_goTypes = []interface{}{
	(EntityType)(0), // 0: gameMessageCore.EntityType
}
var file_proto_entityTypeDefine_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_entityTypeDefine_proto_init() }
func file_proto_entityTypeDefine_proto_init() {
	if File_proto_entityTypeDefine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_entityTypeDefine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_entityTypeDefine_proto_goTypes,
		DependencyIndexes: file_proto_entityTypeDefine_proto_depIdxs,
		EnumInfos:         file_proto_entityTypeDefine_proto_enumTypes,
	}.Build()
	File_proto_entityTypeDefine_proto = out.File
	file_proto_entityTypeDefine_proto_rawDesc = nil
	file_proto_entityTypeDefine_proto_goTypes = nil
	file_proto_entityTypeDefine_proto_depIdxs = nil
}
