// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: grpcMethodData.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务信息用于服务 注册和释放
type ServiceRegisterInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion  int64       `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	Id          int64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name        string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AppId       string      `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ServiceType ServiceType `protobuf:"varint,5,opt,name=service_type,json=serviceType,proto3,enum=gameMessageCore.ServiceType" json:"service_type,omitempty"`
	MapId       int32       `protobuf:"varint,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Host        string      `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	Port        int32       `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	Online      int32       `protobuf:"varint,9,opt,name=online,proto3" json:"online,omitempty"`
	MaxOnline   int32       `protobuf:"varint,10,opt,name=max_online,json=maxOnline,proto3" json:"max_online,omitempty"`
	CreateAt    int64       `protobuf:"varint,11,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt    int64       `protobuf:"varint,12,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
}

func (x *ServiceRegisterInput) Reset() {
	*x = ServiceRegisterInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRegisterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegisterInput) ProtoMessage() {}

func (x *ServiceRegisterInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegisterInput.ProtoReflect.Descriptor instead.
func (*ServiceRegisterInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceRegisterInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *ServiceRegisterInput) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServiceRegisterInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceRegisterInput) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ServiceRegisterInput) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_ServiceTypeUnknown
}

func (x *ServiceRegisterInput) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ServiceRegisterInput) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceRegisterInput) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceRegisterInput) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *ServiceRegisterInput) GetMaxOnline() int32 {
	if x != nil {
		return x.MaxOnline
	}
	return 0
}

func (x *ServiceRegisterInput) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *ServiceRegisterInput) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type ServiceRegisterOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *ServiceRegisterOutput) Reset() {
	*x = ServiceRegisterOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRegisterOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegisterOutput) ProtoMessage() {}

func (x *ServiceRegisterOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegisterOutput.ProtoReflect.Descriptor instead.
func (*ServiceRegisterOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRegisterOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceRegisterOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// 向manager service 查询服务信息
type ManagerActionSelectServiceInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion  int64       `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	ServiceType ServiceType `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=gameMessageCore.ServiceType" json:"service_type,omitempty"`
	MapId       int32       `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
}

func (x *ManagerActionSelectServiceInput) Reset() {
	*x = ManagerActionSelectServiceInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerActionSelectServiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerActionSelectServiceInput) ProtoMessage() {}

func (x *ManagerActionSelectServiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerActionSelectServiceInput.ProtoReflect.Descriptor instead.
func (*ManagerActionSelectServiceInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{2}
}

func (x *ManagerActionSelectServiceInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *ManagerActionSelectServiceInput) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_ServiceTypeUnknown
}

func (x *ManagerActionSelectServiceInput) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type ManagerActionSelectServiceOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode    int32       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string      `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ServiceType  ServiceType `protobuf:"varint,3,opt,name=service_type,json=serviceType,proto3,enum=gameMessageCore.ServiceType" json:"service_type,omitempty"`
	ServiceAppId string      `protobuf:"bytes,4,opt,name=service_app_id,json=serviceAppId,proto3" json:"service_app_id,omitempty"`
	MapId        int32       `protobuf:"varint,5,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Host         string      `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	Port         int32       `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	Online       int32       `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	MaxOnline    int32       `protobuf:"varint,9,opt,name=max_online,json=maxOnline,proto3" json:"max_online,omitempty"`
	CreateAt     int64       `protobuf:"varint,10,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt     int64       `protobuf:"varint,11,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
}

func (x *ManagerActionSelectServiceOutput) Reset() {
	*x = ManagerActionSelectServiceOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerActionSelectServiceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerActionSelectServiceOutput) ProtoMessage() {}

func (x *ManagerActionSelectServiceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerActionSelectServiceOutput.ProtoReflect.Descriptor instead.
func (*ManagerActionSelectServiceOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{3}
}

func (x *ManagerActionSelectServiceOutput) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ManagerActionSelectServiceOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ManagerActionSelectServiceOutput) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_ServiceTypeUnknown
}

func (x *ManagerActionSelectServiceOutput) GetServiceAppId() string {
	if x != nil {
		return x.ServiceAppId
	}
	return ""
}

func (x *ManagerActionSelectServiceOutput) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ManagerActionSelectServiceOutput) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ManagerActionSelectServiceOutput) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ManagerActionSelectServiceOutput) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *ManagerActionSelectServiceOutput) GetMaxOnline() int32 {
	if x != nil {
		return x.MaxOnline
	}
	return 0
}

func (x *ManagerActionSelectServiceOutput) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *ManagerActionSelectServiceOutput) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// agent service forward client message request
type PullClientMessageInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion int64     `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	AgentAppId string    `protobuf:"bytes,2,opt,name=agent_app_id,json=agentAppId,proto3" json:"agent_app_id,omitempty"`
	UserId     int64     `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SocketId   string    `protobuf:"bytes,4,opt,name=socket_id,json=socketId,proto3" json:"socket_id,omitempty"`
	MsgId      int32     `protobuf:"varint,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Msg        *Envelope `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PullClientMessageInput) Reset() {
	*x = PullClientMessageInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullClientMessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullClientMessageInput) ProtoMessage() {}

func (x *PullClientMessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullClientMessageInput.ProtoReflect.Descriptor instead.
func (*PullClientMessageInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{4}
}

func (x *PullClientMessageInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *PullClientMessageInput) GetAgentAppId() string {
	if x != nil {
		return x.AgentAppId
	}
	return ""
}

func (x *PullClientMessageInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PullClientMessageInput) GetSocketId() string {
	if x != nil {
		return x.SocketId
	}
	return ""
}

func (x *PullClientMessageInput) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PullClientMessageInput) GetMsg() *Envelope {
	if x != nil {
		return x.Msg
	}
	return nil
}

type PullClientMessageOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *PullClientMessageOutput) Reset() {
	*x = PullClientMessageOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullClientMessageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullClientMessageOutput) ProtoMessage() {}

func (x *PullClientMessageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullClientMessageOutput.ProtoReflect.Descriptor instead.
func (*PullClientMessageOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{5}
}

func (x *PullClientMessageOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PullClientMessageOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// other service broadcast proto message to client request
type BroadCastToClientInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion   int64     `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	ServiceAppId string    `protobuf:"bytes,2,opt,name=service_app_id,json=serviceAppId,proto3" json:"service_app_id,omitempty"`
	UserId       int64     `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SocketId     string    `protobuf:"bytes,4,opt,name=socket_id,json=socketId,proto3" json:"socket_id,omitempty"`
	MsgId        int32     `protobuf:"varint,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Msg          *Envelope `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BroadCastToClientInput) Reset() {
	*x = BroadCastToClientInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadCastToClientInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastToClientInput) ProtoMessage() {}

func (x *BroadCastToClientInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastToClientInput.ProtoReflect.Descriptor instead.
func (*BroadCastToClientInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{6}
}

func (x *BroadCastToClientInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *BroadCastToClientInput) GetServiceAppId() string {
	if x != nil {
		return x.ServiceAppId
	}
	return ""
}

func (x *BroadCastToClientInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BroadCastToClientInput) GetSocketId() string {
	if x != nil {
		return x.SocketId
	}
	return ""
}

func (x *BroadCastToClientInput) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *BroadCastToClientInput) GetMsg() *Envelope {
	if x != nil {
		return x.Msg
	}
	return nil
}

type BroadCastToClientOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *BroadCastToClientOutput) Reset() {
	*x = BroadCastToClientOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadCastToClientOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadCastToClientOutput) ProtoMessage() {}

func (x *BroadCastToClientOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadCastToClientOutput.ProtoReflect.Descriptor instead.
func (*BroadCastToClientOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{7}
}

func (x *BroadCastToClientOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadCastToClientOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// other service multiple broadcast proto message to client request
type MultipleBroadCastToClientInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion   int64     `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	ServiceAppId string    `protobuf:"bytes,2,opt,name=service_app_id,json=serviceAppId,proto3" json:"service_app_id,omitempty"`
	UserList     []int64   `protobuf:"varint,3,rep,packed,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	MsgId        int32     `protobuf:"varint,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Msg          *Envelope `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MultipleBroadCastToClientInput) Reset() {
	*x = MultipleBroadCastToClientInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleBroadCastToClientInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleBroadCastToClientInput) ProtoMessage() {}

func (x *MultipleBroadCastToClientInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleBroadCastToClientInput.ProtoReflect.Descriptor instead.
func (*MultipleBroadCastToClientInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{8}
}

func (x *MultipleBroadCastToClientInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *MultipleBroadCastToClientInput) GetServiceAppId() string {
	if x != nil {
		return x.ServiceAppId
	}
	return ""
}

func (x *MultipleBroadCastToClientInput) GetUserList() []int64 {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *MultipleBroadCastToClientInput) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MultipleBroadCastToClientInput) GetMsg() *Envelope {
	if x != nil {
		return x.Msg
	}
	return nil
}

type MultipleBroadCastToClientOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *MultipleBroadCastToClientOutput) Reset() {
	*x = MultipleBroadCastToClientOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleBroadCastToClientOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleBroadCastToClientOutput) ProtoMessage() {}

func (x *MultipleBroadCastToClientOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleBroadCastToClientOutput.ProtoReflect.Descriptor instead.
func (*MultipleBroadCastToClientOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{9}
}

func (x *MultipleBroadCastToClientOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MultipleBroadCastToClientOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// user leave game
type UserLeaveGameInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion   int64  `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	ServiceAppId string `protobuf:"bytes,2,opt,name=service_app_id,json=serviceAppId,proto3" json:"service_app_id,omitempty"`
	UserId       int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserLeaveGameInput) Reset() {
	*x = UserLeaveGameInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLeaveGameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeaveGameInput) ProtoMessage() {}

func (x *UserLeaveGameInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeaveGameInput.ProtoReflect.Descriptor instead.
func (*UserLeaveGameInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{10}
}

func (x *UserLeaveGameInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *UserLeaveGameInput) GetServiceAppId() string {
	if x != nil {
		return x.ServiceAppId
	}
	return ""
}

func (x *UserLeaveGameInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserLeaveGameOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *UserLeaveGameOutput) Reset() {
	*x = UserLeaveGameOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLeaveGameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeaveGameOutput) ProtoMessage() {}

func (x *UserLeaveGameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeaveGameOutput.ProtoReflect.Descriptor instead.
func (*UserLeaveGameOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{11}
}

func (x *UserLeaveGameOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserLeaveGameOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// 更新玩家使用的装备
type UpdateUsedAvatarInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion   int64           `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	UserId       int64           `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UsingAvatars []*PlayerAvatar `protobuf:"bytes,3,rep,name=using_avatars,json=usingAvatars,proto3" json:"using_avatars,omitempty"`
	CurProfile   *EntityProfile  `protobuf:"bytes,4,opt,name=cur_profile,json=curProfile,proto3" json:"cur_profile,omitempty"`
}

func (x *UpdateUsedAvatarInput) Reset() {
	*x = UpdateUsedAvatarInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUsedAvatarInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsedAvatarInput) ProtoMessage() {}

func (x *UpdateUsedAvatarInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsedAvatarInput.ProtoReflect.Descriptor instead.
func (*UpdateUsedAvatarInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUsedAvatarInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *UpdateUsedAvatarInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUsedAvatarInput) GetUsingAvatars() []*PlayerAvatar {
	if x != nil {
		return x.UsingAvatars
	}
	return nil
}

func (x *UpdateUsedAvatarInput) GetCurProfile() *EntityProfile {
	if x != nil {
		return x.CurProfile
	}
	return nil
}

type UpdateUsedAvatarOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *UpdateUsedAvatarOutput) Reset() {
	*x = UpdateUsedAvatarOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUsedAvatarOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsedAvatarOutput) ProtoMessage() {}

func (x *UpdateUsedAvatarOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsedAvatarOutput.ProtoReflect.Descriptor instead.
func (*UpdateUsedAvatarOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUsedAvatarOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUsedAvatarOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// 更新玩家战斗属性(升级/装备槽等级变更)
type UpdateUserProfileInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion int64          `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	UserId     int64          `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurProfile *EntityProfile `protobuf:"bytes,3,opt,name=cur_profile,json=curProfile,proto3" json:"cur_profile,omitempty"`
}

func (x *UpdateUserProfileInput) Reset() {
	*x = UpdateUserProfileInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserProfileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileInput) ProtoMessage() {}

func (x *UpdateUserProfileInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileInput.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserProfileInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *UpdateUserProfileInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserProfileInput) GetCurProfile() *EntityProfile {
	if x != nil {
		return x.CurProfile
	}
	return nil
}

type UpdateUserProfileOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *UpdateUserProfileOutput) Reset() {
	*x = UpdateUserProfileOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserProfileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileOutput) ProtoMessage() {}

func (x *UpdateUserProfileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileOutput.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserProfileOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserProfileOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// 获取user 详细数据
type GetUserDataInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgVersion int64 `protobuf:"varint,1,opt,name=msg_version,json=msgVersion,proto3" json:"msg_version,omitempty"`
	UserId     int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserDataInput) Reset() {
	*x = GetUserDataInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDataInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataInput) ProtoMessage() {}

func (x *GetUserDataInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataInput.ProtoReflect.Descriptor instead.
func (*GetUserDataInput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserDataInput) GetMsgVersion() int64 {
	if x != nil {
		return x.MsgVersion
	}
	return 0
}

func (x *GetUserDataInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserDataOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg   string          `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	BaseData *PlayerBaseData `protobuf:"bytes,3,opt,name=base_data,json=baseData,proto3" json:"base_data,omitempty"`
	Profile  *EntityProfile  `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	MapId    int32           `protobuf:"varint,5,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Position *Vector3        `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	Dir      *Vector3        `protobuf:"bytes,7,opt,name=dir,proto3" json:"dir,omitempty"`
	Avatars  []*PlayerAvatar `protobuf:"bytes,8,rep,name=avatars,proto3" json:"avatars,omitempty"`
}

func (x *GetUserDataOutput) Reset() {
	*x = GetUserDataOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcMethodData_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDataOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataOutput) ProtoMessage() {}

func (x *GetUserDataOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpcMethodData_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataOutput.ProtoReflect.Descriptor instead.
func (*GetUserDataOutput) Descriptor() ([]byte, []int) {
	return file_grpcMethodData_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserDataOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserDataOutput) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetUserDataOutput) GetBaseData() *PlayerBaseData {
	if x != nil {
		return x.BaseData
	}
	return nil
}

func (x *GetUserDataOutput) GetProfile() *EntityProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetUserDataOutput) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *GetUserDataOutput) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GetUserDataOutput) GetDir() *Vector3 {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *GetUserDataOutput) GetAvatars() []*PlayerAvatar {
	if x != nil {
		return x.Avatars
	}
	return nil
}

var File_grpcMethodData_proto protoreflect.FileDescriptor

var file_grpcMethodData_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x1a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x69, 0x74, 0x65, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x02, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x61, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x4a, 0x0a,
	0x15, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x9a, 0x01, 0x0a, 0x1f, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3f,
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0xfd, 0x02, 0x0a, 0x20, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3f, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0xd5, 0x01, 0x0a, 0x16, 0x50, 0x75, 0x6c, 0x6c, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x2b, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65,
	0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4c,
	0x0a, 0x17, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0xd9, 0x01, 0x0a,
	0x16, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x73,
	0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4c, 0x0a, 0x17, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x43, 0x61, 0x73, 0x74, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0xc8, 0x01, 0x0a, 0x1e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x54, 0x6f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x6d, 0x73, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x54, 0x0a, 0x1f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x74, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x48, 0x0a,
	0x13, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0xd6, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x0d, 0x75,
	0x73, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x52, 0x0c, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x12,
	0x3f, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0x4b, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x64, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x93, 0x01,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d,
	0x73, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x22, 0x4c, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0x4c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0xf0, 0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x3c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x62, 0x61,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x33, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a,
	0x03, 0x64, 0x69, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x33, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x37, 0x0a, 0x07, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x07, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcMethodData_proto_rawDescOnce sync.Once
	file_grpcMethodData_proto_rawDescData = file_grpcMethodData_proto_rawDesc
)

func file_grpcMethodData_proto_rawDescGZIP() []byte {
	file_grpcMethodData_proto_rawDescOnce.Do(func() {
		file_grpcMethodData_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcMethodData_proto_rawDescData)
	})
	return file_grpcMethodData_proto_rawDescData
}

var file_grpcMethodData_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_grpcMethodData_proto_goTypes = []interface{}{
	(*ServiceRegisterInput)(nil),             // 0: gameMessageCore.ServiceRegisterInput
	(*ServiceRegisterOutput)(nil),            // 1: gameMessageCore.ServiceRegisterOutput
	(*ManagerActionSelectServiceInput)(nil),  // 2: gameMessageCore.ManagerActionSelectServiceInput
	(*ManagerActionSelectServiceOutput)(nil), // 3: gameMessageCore.ManagerActionSelectServiceOutput
	(*PullClientMessageInput)(nil),           // 4: gameMessageCore.PullClientMessageInput
	(*PullClientMessageOutput)(nil),          // 5: gameMessageCore.PullClientMessageOutput
	(*BroadCastToClientInput)(nil),           // 6: gameMessageCore.BroadCastToClientInput
	(*BroadCastToClientOutput)(nil),          // 7: gameMessageCore.BroadCastToClientOutput
	(*MultipleBroadCastToClientInput)(nil),   // 8: gameMessageCore.MultipleBroadCastToClientInput
	(*MultipleBroadCastToClientOutput)(nil),  // 9: gameMessageCore.MultipleBroadCastToClientOutput
	(*UserLeaveGameInput)(nil),               // 10: gameMessageCore.UserLeaveGameInput
	(*UserLeaveGameOutput)(nil),              // 11: gameMessageCore.UserLeaveGameOutput
	(*UpdateUsedAvatarInput)(nil),            // 12: gameMessageCore.UpdateUsedAvatarInput
	(*UpdateUsedAvatarOutput)(nil),           // 13: gameMessageCore.UpdateUsedAvatarOutput
	(*UpdateUserProfileInput)(nil),           // 14: gameMessageCore.UpdateUserProfileInput
	(*UpdateUserProfileOutput)(nil),          // 15: gameMessageCore.UpdateUserProfileOutput
	(*GetUserDataInput)(nil),                 // 16: gameMessageCore.GetUserDataInput
	(*GetUserDataOutput)(nil),                // 17: gameMessageCore.GetUserDataOutput
	(ServiceType)(0),                         // 18: gameMessageCore.ServiceType
	(*Envelope)(nil),                         // 19: gameMessageCore.Envelope
	(*PlayerAvatar)(nil),                     // 20: gameMessageCore.PlayerAvatar
	(*EntityProfile)(nil),                    // 21: gameMessageCore.EntityProfile
	(*PlayerBaseData)(nil),                   // 22: gameMessageCore.PlayerBaseData
	(*Vector3)(nil),                          // 23: gameMessageCore.Vector3
}
var file_grpcMethodData_proto_depIdxs = []int32{
	18, // 0: gameMessageCore.ServiceRegisterInput.service_type:type_name -> gameMessageCore.ServiceType
	18, // 1: gameMessageCore.ManagerActionSelectServiceInput.service_type:type_name -> gameMessageCore.ServiceType
	18, // 2: gameMessageCore.ManagerActionSelectServiceOutput.service_type:type_name -> gameMessageCore.ServiceType
	19, // 3: gameMessageCore.PullClientMessageInput.msg:type_name -> gameMessageCore.Envelope
	19, // 4: gameMessageCore.BroadCastToClientInput.msg:type_name -> gameMessageCore.Envelope
	19, // 5: gameMessageCore.MultipleBroadCastToClientInput.msg:type_name -> gameMessageCore.Envelope
	20, // 6: gameMessageCore.UpdateUsedAvatarInput.using_avatars:type_name -> gameMessageCore.PlayerAvatar
	21, // 7: gameMessageCore.UpdateUsedAvatarInput.cur_profile:type_name -> gameMessageCore.EntityProfile
	21, // 8: gameMessageCore.UpdateUserProfileInput.cur_profile:type_name -> gameMessageCore.EntityProfile
	22, // 9: gameMessageCore.GetUserDataOutput.base_data:type_name -> gameMessageCore.PlayerBaseData
	21, // 10: gameMessageCore.GetUserDataOutput.profile:type_name -> gameMessageCore.EntityProfile
	23, // 11: gameMessageCore.GetUserDataOutput.position:type_name -> gameMessageCore.Vector3
	23, // 12: gameMessageCore.GetUserDataOutput.dir:type_name -> gameMessageCore.Vector3
	20, // 13: gameMessageCore.GetUserDataOutput.avatars:type_name -> gameMessageCore.PlayerAvatar
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_grpcMethodData_proto_init() }
func file_grpcMethodData_proto_init() {
	if File_grpcMethodData_proto != nil {
		return
	}
	file_message_body_proto_init()
	file_service_proto_init()
	file_item_proto_init()
	file_entityProfile_proto_init()
	file_player_proto_init()
	file_vector_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpcMethodData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRegisterInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRegisterOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerActionSelectServiceInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerActionSelectServiceOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullClientMessageInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullClientMessageOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadCastToClientInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadCastToClientOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipleBroadCastToClientInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipleBroadCastToClientOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLeaveGameInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLeaveGameOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUsedAvatarInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUsedAvatarOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserProfileInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserProfileOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDataInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcMethodData_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDataOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcMethodData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcMethodData_proto_goTypes,
		DependencyIndexes: file_grpcMethodData_proto_depIdxs,
		MessageInfos:      file_grpcMethodData_proto_msgTypes,
	}.Build()
	File_grpcMethodData_proto = out.File
	file_grpcMethodData_proto_rawDesc = nil
	file_grpcMethodData_proto_goTypes = nil
	file_grpcMethodData_proto_depIdxs = nil
}
