// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: proto/item_slot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemSlotAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// HP limit
	HpLimitAdded int32 `protobuf:"varint,1,opt,name=hp_limit_added,json=hpLimitAdded,proto3" json:"hp_limit_added,omitempty"`
	// HP Recovery
	HpRecoveryAdded int32 `protobuf:"varint,2,opt,name=hp_recovery_added,json=hpRecoveryAdded,proto3" json:"hp_recovery_added,omitempty"`
	// 增加普通攻击
	AttAdded int32 `protobuf:"varint,3,opt,name=att_added,json=attAdded,proto3" json:"att_added,omitempty"`
	// 增加普通攻击速度
	AttSpeedAdded int32 `protobuf:"varint,4,opt,name=att_speed_added,json=attSpeedAdded,proto3" json:"att_speed_added,omitempty"`
	// 增加普通防御
	DefAdded int32 `protobuf:"varint,5,opt,name=def_added,json=defAdded,proto3" json:"def_added,omitempty"`
	// 增加暴击率
	CritRateAdded int32 `protobuf:"varint,6,opt,name=crit_rate_added,json=critRateAdded,proto3" json:"crit_rate_added,omitempty"`
	// 增加暴击伤害
	CritDmgAdded int32 `protobuf:"varint,7,opt,name=crit_dmg_added,json=critDmgAdded,proto3" json:"crit_dmg_added,omitempty"`
	// 增加命中率
	HitRateAdded int32 `protobuf:"varint,8,opt,name=hit_rate_added,json=hitRateAdded,proto3" json:"hit_rate_added,omitempty"`
	// 增加闪避率
	MissRateAdded int32 `protobuf:"varint,9,opt,name=miss_rate_added,json=missRateAdded,proto3" json:"miss_rate_added,omitempty"`
	// 移动速度
	MoveSpeedAdded int32 `protobuf:"varint,10,opt,name=move_speed_added,json=moveSpeedAdded,proto3" json:"move_speed_added,omitempty"`
}

func (x *ItemSlotAttribute) Reset() {
	*x = ItemSlotAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_item_slot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSlotAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSlotAttribute) ProtoMessage() {}

func (x *ItemSlotAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_slot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSlotAttribute.ProtoReflect.Descriptor instead.
func (*ItemSlotAttribute) Descriptor() ([]byte, []int) {
	return file_proto_item_slot_proto_rawDescGZIP(), []int{0}
}

func (x *ItemSlotAttribute) GetHpLimitAdded() int32 {
	if x != nil {
		return x.HpLimitAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetHpRecoveryAdded() int32 {
	if x != nil {
		return x.HpRecoveryAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetAttAdded() int32 {
	if x != nil {
		return x.AttAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetAttSpeedAdded() int32 {
	if x != nil {
		return x.AttSpeedAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetDefAdded() int32 {
	if x != nil {
		return x.DefAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetCritRateAdded() int32 {
	if x != nil {
		return x.CritRateAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetCritDmgAdded() int32 {
	if x != nil {
		return x.CritDmgAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetHitRateAdded() int32 {
	if x != nil {
		return x.HitRateAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetMissRateAdded() int32 {
	if x != nil {
		return x.MissRateAdded
	}
	return 0
}

func (x *ItemSlotAttribute) GetMoveSpeedAdded() int32 {
	if x != nil {
		return x.MoveSpeedAdded
	}
	return 0
}

type ItemSlotSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 道具槽位置 遵循 AvatarPosition 规则
	Position int32 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Lv       int32 `protobuf:"varint,2,opt,name=lv,proto3" json:"lv,omitempty"`
	// 升级下一级消耗的经验
	UpExp int32 `protobuf:"varint,3,opt,name=up_exp,json=upExp,proto3" json:"up_exp,omitempty"`
	// 升级下一级消耗的meld
	UpMeld int32 `protobuf:"varint,4,opt,name=up_meld,json=upMeld,proto3" json:"up_meld,omitempty"`
	// 属性加成信息
	Attribute *ItemSlotAttribute `protobuf:"bytes,5,opt,name=attribute,proto3" json:"attribute,omitempty"`
}

func (x *ItemSlotSetting) Reset() {
	*x = ItemSlotSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_item_slot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSlotSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSlotSetting) ProtoMessage() {}

func (x *ItemSlotSetting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_slot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSlotSetting.ProtoReflect.Descriptor instead.
func (*ItemSlotSetting) Descriptor() ([]byte, []int) {
	return file_proto_item_slot_proto_rawDescGZIP(), []int{1}
}

func (x *ItemSlotSetting) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ItemSlotSetting) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *ItemSlotSetting) GetUpExp() int32 {
	if x != nil {
		return x.UpExp
	}
	return 0
}

func (x *ItemSlotSetting) GetUpMeld() int32 {
	if x != nil {
		return x.UpMeld
	}
	return 0
}

func (x *ItemSlotSetting) GetAttribute() *ItemSlotAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type ItemSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ItemSlot) Reset() {
	*x = ItemSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_item_slot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSlot) ProtoMessage() {}

func (x *ItemSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_slot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSlot.ProtoReflect.Descriptor instead.
func (*ItemSlot) Descriptor() ([]byte, []int) {
	return file_proto_item_slot_proto_rawDescGZIP(), []int{2}
}

var File_proto_item_slot_proto protoreflect.FileDescriptor

var file_proto_item_slot_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x6c, 0x6f,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x03, 0x0a,
	0x11, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x68, 0x70, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x61,
	0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x68, 0x70, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x70, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0f, 0x68, 0x70, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x41,
	0x64, 0x64, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x41, 0x64, 0x64, 0x65,
	0x64, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x5f, 0x61,
	0x64, 0x64, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x53,
	0x70, 0x65, 0x65, 0x64, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x66,
	0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65,
	0x66, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x72, 0x69, 0x74, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x63, 0x72, 0x69, 0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x24,
	0x0a, 0x0e, 0x63, 0x72, 0x69, 0x74, 0x5f, 0x64, 0x6d, 0x67, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x72, 0x69, 0x74, 0x44, 0x6d, 0x67, 0x41,
	0x64, 0x64, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x68, 0x69, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x65,
	0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x68, 0x69,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x69,
	0x73, 0x73, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x52, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64,
	0x65, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x70, 0x65, 0x65, 0x64, 0x41, 0x64, 0x64, 0x65, 0x64, 0x22, 0xaf, 0x01, 0x0a,
	0x0f, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x6c, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x12, 0x15, 0x0a, 0x06,
	0x75, 0x70, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x70,
	0x45, 0x78, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x70, 0x5f, 0x6d, 0x65, 0x6c, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x70, 0x4d, 0x65, 0x6c, 0x64, 0x12, 0x40, 0x0a, 0x09,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72,
	0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x0a,
	0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_item_slot_proto_rawDescOnce sync.Once
	file_proto_item_slot_proto_rawDescData = file_proto_item_slot_proto_rawDesc
)

func file_proto_item_slot_proto_rawDescGZIP() []byte {
	file_proto_item_slot_proto_rawDescOnce.Do(func() {
		file_proto_item_slot_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_item_slot_proto_rawDescData)
	})
	return file_proto_item_slot_proto_rawDescData
}

var file_proto_item_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_item_slot_proto_goTypes = []interface{}{
	(*ItemSlotAttribute)(nil), // 0: gameMessageCore.ItemSlotAttribute
	(*ItemSlotSetting)(nil),   // 1: gameMessageCore.ItemSlotSetting
	(*ItemSlot)(nil),          // 2: gameMessageCore.ItemSlot
}
var file_proto_item_slot_proto_depIdxs = []int32{
	0, // 0: gameMessageCore.ItemSlotSetting.attribute:type_name -> gameMessageCore.ItemSlotAttribute
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_item_slot_proto_init() }
func file_proto_item_slot_proto_init() {
	if File_proto_item_slot_proto != nil {
		return
	}
	file_proto_vector_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_item_slot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSlotAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_item_slot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSlotSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_item_slot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_item_slot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_item_slot_proto_goTypes,
		DependencyIndexes: file_proto_item_slot_proto_depIdxs,
		MessageInfos:      file_proto_item_slot_proto_msgTypes,
	}.Build()
	File_proto_item_slot_proto = out.File
	file_proto_item_slot_proto_rawDesc = nil
	file_proto_item_slot_proto_goTypes = nil
	file_proto_item_slot_proto_depIdxs = nil
}
