// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameMessageCore {

  /// <summary>Holder for reflection information generated from game_log.proto</summary>
  public static partial class GameLogReflection {

    #region Descriptor
    /// <summary>File descriptor for game_log.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameLogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5nYW1lX2xvZy5wcm90bxIPZ2FtZU1lc3NhZ2VDb3JlKpsCCgtHYW1lTG9n",
            "VHlwZRIOCgpsb2dfdW5rbm93EAASDwoLY3JlYXRlX3VzZXIQARIOCgplbnRl",
            "cl9nYW1lEAISDgoKbGVhdmVfZ2FtZRADEhAKDGtpbGxfbW9uc3RlchAEEhIK",
            "DmNhcHR1cmVfYW5pbWFsEAUSDwoLZnJlZV9hbmltYWwQBhIPCgthY2NlcHRf",
            "dGFzaxAHEhAKDGFiYW5kb25fdGFzaxAIEg8KC2ZpbmlzaF90YXNrEAkSFAoQ",
            "YWNjZXB0X3Rhc2tfbGlzdBAKEhUKEWFiYW5kb25fdGFza19saXN0EAsSFAoQ",
            "ZmluaXNoX3Rhc2tfbGlzdBAMEg4KCmVudGVyX2hvbWUQDRINCglxdWl0X2hv",
            "bWUQDmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameMessageCore.GameLogType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GameLogType {
    [pbr::OriginalName("log_unknow")] LogUnknow = 0,
    [pbr::OriginalName("create_user")] CreateUser = 1,
    [pbr::OriginalName("enter_game")] EnterGame = 2,
    [pbr::OriginalName("leave_game")] LeaveGame = 3,
    [pbr::OriginalName("kill_monster")] KillMonster = 4,
    [pbr::OriginalName("capture_animal")] CaptureAnimal = 5,
    [pbr::OriginalName("free_animal")] FreeAnimal = 6,
    [pbr::OriginalName("accept_task")] AcceptTask = 7,
    [pbr::OriginalName("abandon_task")] AbandonTask = 8,
    [pbr::OriginalName("finish_task")] FinishTask = 9,
    [pbr::OriginalName("accept_task_list")] AcceptTaskList = 10,
    [pbr::OriginalName("abandon_task_list")] AbandonTaskList = 11,
    [pbr::OriginalName("finish_task_list")] FinishTaskList = 12,
    [pbr::OriginalName("enter_home")] EnterHome = 13,
    [pbr::OriginalName("quit_home")] QuitHome = 14,
  }

  #endregion

}

#endregion Designer generated code
