// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: item_slot.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameMessageCore {

  /// <summary>Holder for reflection information generated from item_slot.proto</summary>
  public static partial class ItemSlotReflection {

    #region Descriptor
    /// <summary>File descriptor for item_slot.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemSlotReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9pdGVtX3Nsb3QucHJvdG8SD2dhbWVNZXNzYWdlQ29yZRoKaXRlbS5wcm90",
            "byKBAgoRSXRlbVNsb3RBdHRyaWJ1dGUSFgoOaHBfbGltaXRfYWRkZWQYASAB",
            "KAUSGQoRaHBfcmVjb3ZlcnlfYWRkZWQYAiABKAUSEQoJYXR0X2FkZGVkGAMg",
            "ASgFEhcKD2F0dF9zcGVlZF9hZGRlZBgEIAEoBRIRCglkZWZfYWRkZWQYBSAB",
            "KAUSFwoPY3JpdF9yYXRlX2FkZGVkGAYgASgFEhYKDmNyaXRfZG1nX2FkZGVk",
            "GAcgASgFEhYKDmhpdF9yYXRlX2FkZGVkGAggASgFEhcKD21pc3NfcmF0ZV9h",
            "ZGRlZBgJIAEoBRIYChBtb3ZlX3NwZWVkX2FkZGVkGAogASgFIkwKCEl0ZW1T",
            "bG90EjEKCHBvc2l0aW9uGAEgASgOMh8uZ2FtZU1lc3NhZ2VDb3JlLkF2YXRh",
            "clBvc2l0aW9uEg0KBWxldmVsGAIgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameMessageCore.ItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessageCore.ItemSlotAttribute), global::GameMessageCore.ItemSlotAttribute.Parser, new[]{ "HpLimitAdded", "HpRecoveryAdded", "AttAdded", "AttSpeedAdded", "DefAdded", "CritRateAdded", "CritDmgAdded", "HitRateAdded", "MissRateAdded", "MoveSpeedAdded" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessageCore.ItemSlot), global::GameMessageCore.ItemSlot.Parser, new[]{ "Position", "Level" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ItemSlotAttribute : pb::IMessage<ItemSlotAttribute>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemSlotAttribute> _parser = new pb::MessageParser<ItemSlotAttribute>(() => new ItemSlotAttribute());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemSlotAttribute> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessageCore.ItemSlotReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemSlotAttribute() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemSlotAttribute(ItemSlotAttribute other) : this() {
      hpLimitAdded_ = other.hpLimitAdded_;
      hpRecoveryAdded_ = other.hpRecoveryAdded_;
      attAdded_ = other.attAdded_;
      attSpeedAdded_ = other.attSpeedAdded_;
      defAdded_ = other.defAdded_;
      critRateAdded_ = other.critRateAdded_;
      critDmgAdded_ = other.critDmgAdded_;
      hitRateAdded_ = other.hitRateAdded_;
      missRateAdded_ = other.missRateAdded_;
      moveSpeedAdded_ = other.moveSpeedAdded_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemSlotAttribute Clone() {
      return new ItemSlotAttribute(this);
    }

    /// <summary>Field number for the "hp_limit_added" field.</summary>
    public const int HpLimitAddedFieldNumber = 1;
    private int hpLimitAdded_;
    /// <summary>
    /// HP limit
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HpLimitAdded {
      get { return hpLimitAdded_; }
      set {
        hpLimitAdded_ = value;
      }
    }

    /// <summary>Field number for the "hp_recovery_added" field.</summary>
    public const int HpRecoveryAddedFieldNumber = 2;
    private int hpRecoveryAdded_;
    /// <summary>
    /// HP Recovery
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HpRecoveryAdded {
      get { return hpRecoveryAdded_; }
      set {
        hpRecoveryAdded_ = value;
      }
    }

    /// <summary>Field number for the "att_added" field.</summary>
    public const int AttAddedFieldNumber = 3;
    private int attAdded_;
    /// <summary>
    /// 增加普通攻击
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttAdded {
      get { return attAdded_; }
      set {
        attAdded_ = value;
      }
    }

    /// <summary>Field number for the "att_speed_added" field.</summary>
    public const int AttSpeedAddedFieldNumber = 4;
    private int attSpeedAdded_;
    /// <summary>
    /// 增加普通攻击速度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttSpeedAdded {
      get { return attSpeedAdded_; }
      set {
        attSpeedAdded_ = value;
      }
    }

    /// <summary>Field number for the "def_added" field.</summary>
    public const int DefAddedFieldNumber = 5;
    private int defAdded_;
    /// <summary>
    /// 增加普通防御
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DefAdded {
      get { return defAdded_; }
      set {
        defAdded_ = value;
      }
    }

    /// <summary>Field number for the "crit_rate_added" field.</summary>
    public const int CritRateAddedFieldNumber = 6;
    private int critRateAdded_;
    /// <summary>
    /// 增加暴击率
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CritRateAdded {
      get { return critRateAdded_; }
      set {
        critRateAdded_ = value;
      }
    }

    /// <summary>Field number for the "crit_dmg_added" field.</summary>
    public const int CritDmgAddedFieldNumber = 7;
    private int critDmgAdded_;
    /// <summary>
    /// 增加暴击伤害
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CritDmgAdded {
      get { return critDmgAdded_; }
      set {
        critDmgAdded_ = value;
      }
    }

    /// <summary>Field number for the "hit_rate_added" field.</summary>
    public const int HitRateAddedFieldNumber = 8;
    private int hitRateAdded_;
    /// <summary>
    /// 增加命中率
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HitRateAdded {
      get { return hitRateAdded_; }
      set {
        hitRateAdded_ = value;
      }
    }

    /// <summary>Field number for the "miss_rate_added" field.</summary>
    public const int MissRateAddedFieldNumber = 9;
    private int missRateAdded_;
    /// <summary>
    /// 增加闪避率
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MissRateAdded {
      get { return missRateAdded_; }
      set {
        missRateAdded_ = value;
      }
    }

    /// <summary>Field number for the "move_speed_added" field.</summary>
    public const int MoveSpeedAddedFieldNumber = 10;
    private int moveSpeedAdded_;
    /// <summary>
    /// 移动速度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MoveSpeedAdded {
      get { return moveSpeedAdded_; }
      set {
        moveSpeedAdded_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemSlotAttribute);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemSlotAttribute other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HpLimitAdded != other.HpLimitAdded) return false;
      if (HpRecoveryAdded != other.HpRecoveryAdded) return false;
      if (AttAdded != other.AttAdded) return false;
      if (AttSpeedAdded != other.AttSpeedAdded) return false;
      if (DefAdded != other.DefAdded) return false;
      if (CritRateAdded != other.CritRateAdded) return false;
      if (CritDmgAdded != other.CritDmgAdded) return false;
      if (HitRateAdded != other.HitRateAdded) return false;
      if (MissRateAdded != other.MissRateAdded) return false;
      if (MoveSpeedAdded != other.MoveSpeedAdded) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HpLimitAdded != 0) hash ^= HpLimitAdded.GetHashCode();
      if (HpRecoveryAdded != 0) hash ^= HpRecoveryAdded.GetHashCode();
      if (AttAdded != 0) hash ^= AttAdded.GetHashCode();
      if (AttSpeedAdded != 0) hash ^= AttSpeedAdded.GetHashCode();
      if (DefAdded != 0) hash ^= DefAdded.GetHashCode();
      if (CritRateAdded != 0) hash ^= CritRateAdded.GetHashCode();
      if (CritDmgAdded != 0) hash ^= CritDmgAdded.GetHashCode();
      if (HitRateAdded != 0) hash ^= HitRateAdded.GetHashCode();
      if (MissRateAdded != 0) hash ^= MissRateAdded.GetHashCode();
      if (MoveSpeedAdded != 0) hash ^= MoveSpeedAdded.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HpLimitAdded != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(HpLimitAdded);
      }
      if (HpRecoveryAdded != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(HpRecoveryAdded);
      }
      if (AttAdded != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AttAdded);
      }
      if (AttSpeedAdded != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AttSpeedAdded);
      }
      if (DefAdded != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DefAdded);
      }
      if (CritRateAdded != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CritRateAdded);
      }
      if (CritDmgAdded != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CritDmgAdded);
      }
      if (HitRateAdded != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(HitRateAdded);
      }
      if (MissRateAdded != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(MissRateAdded);
      }
      if (MoveSpeedAdded != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(MoveSpeedAdded);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HpLimitAdded != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(HpLimitAdded);
      }
      if (HpRecoveryAdded != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(HpRecoveryAdded);
      }
      if (AttAdded != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AttAdded);
      }
      if (AttSpeedAdded != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AttSpeedAdded);
      }
      if (DefAdded != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DefAdded);
      }
      if (CritRateAdded != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CritRateAdded);
      }
      if (CritDmgAdded != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CritDmgAdded);
      }
      if (HitRateAdded != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(HitRateAdded);
      }
      if (MissRateAdded != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(MissRateAdded);
      }
      if (MoveSpeedAdded != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(MoveSpeedAdded);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HpLimitAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HpLimitAdded);
      }
      if (HpRecoveryAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HpRecoveryAdded);
      }
      if (AttAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttAdded);
      }
      if (AttSpeedAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttSpeedAdded);
      }
      if (DefAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DefAdded);
      }
      if (CritRateAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CritRateAdded);
      }
      if (CritDmgAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CritDmgAdded);
      }
      if (HitRateAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HitRateAdded);
      }
      if (MissRateAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MissRateAdded);
      }
      if (MoveSpeedAdded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MoveSpeedAdded);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemSlotAttribute other) {
      if (other == null) {
        return;
      }
      if (other.HpLimitAdded != 0) {
        HpLimitAdded = other.HpLimitAdded;
      }
      if (other.HpRecoveryAdded != 0) {
        HpRecoveryAdded = other.HpRecoveryAdded;
      }
      if (other.AttAdded != 0) {
        AttAdded = other.AttAdded;
      }
      if (other.AttSpeedAdded != 0) {
        AttSpeedAdded = other.AttSpeedAdded;
      }
      if (other.DefAdded != 0) {
        DefAdded = other.DefAdded;
      }
      if (other.CritRateAdded != 0) {
        CritRateAdded = other.CritRateAdded;
      }
      if (other.CritDmgAdded != 0) {
        CritDmgAdded = other.CritDmgAdded;
      }
      if (other.HitRateAdded != 0) {
        HitRateAdded = other.HitRateAdded;
      }
      if (other.MissRateAdded != 0) {
        MissRateAdded = other.MissRateAdded;
      }
      if (other.MoveSpeedAdded != 0) {
        MoveSpeedAdded = other.MoveSpeedAdded;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HpLimitAdded = input.ReadInt32();
            break;
          }
          case 16: {
            HpRecoveryAdded = input.ReadInt32();
            break;
          }
          case 24: {
            AttAdded = input.ReadInt32();
            break;
          }
          case 32: {
            AttSpeedAdded = input.ReadInt32();
            break;
          }
          case 40: {
            DefAdded = input.ReadInt32();
            break;
          }
          case 48: {
            CritRateAdded = input.ReadInt32();
            break;
          }
          case 56: {
            CritDmgAdded = input.ReadInt32();
            break;
          }
          case 64: {
            HitRateAdded = input.ReadInt32();
            break;
          }
          case 72: {
            MissRateAdded = input.ReadInt32();
            break;
          }
          case 80: {
            MoveSpeedAdded = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HpLimitAdded = input.ReadInt32();
            break;
          }
          case 16: {
            HpRecoveryAdded = input.ReadInt32();
            break;
          }
          case 24: {
            AttAdded = input.ReadInt32();
            break;
          }
          case 32: {
            AttSpeedAdded = input.ReadInt32();
            break;
          }
          case 40: {
            DefAdded = input.ReadInt32();
            break;
          }
          case 48: {
            CritRateAdded = input.ReadInt32();
            break;
          }
          case 56: {
            CritDmgAdded = input.ReadInt32();
            break;
          }
          case 64: {
            HitRateAdded = input.ReadInt32();
            break;
          }
          case 72: {
            MissRateAdded = input.ReadInt32();
            break;
          }
          case 80: {
            MoveSpeedAdded = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ItemSlot : pb::IMessage<ItemSlot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemSlot> _parser = new pb::MessageParser<ItemSlot>(() => new ItemSlot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemSlot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessageCore.ItemSlotReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemSlot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemSlot(ItemSlot other) : this() {
      position_ = other.position_;
      level_ = other.level_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemSlot Clone() {
      return new ItemSlot(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private global::GameMessageCore.AvatarPosition position_ = global::GameMessageCore.AvatarPosition.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameMessageCore.AvatarPosition Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemSlot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemSlot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Position != other.Position) return false;
      if (Level != other.Level) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Position != global::GameMessageCore.AvatarPosition.None) hash ^= Position.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Position != global::GameMessageCore.AvatarPosition.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Position);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Position != global::GameMessageCore.AvatarPosition.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Position);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Position != global::GameMessageCore.AvatarPosition.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Position);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemSlot other) {
      if (other == null) {
        return;
      }
      if (other.Position != global::GameMessageCore.AvatarPosition.None) {
        Position = other.Position;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Position = (global::GameMessageCore.AvatarPosition) input.ReadEnum();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Position = (global::GameMessageCore.AvatarPosition) input.ReadEnum();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
